#!/bin/bash

/home/breadbox/p/html2txt < ./README.html > ./README
/home/breadbox/p/html2txt < ./BUGS.html > ./BUGS
/home/breadbox/p/html2txt < ./INSTALL.html > ./INSTALL
/home/breadbox/p/html2txt < ./Changelog.html > ./Changelog

VER=`tr -cd 0123456789. < ver.h`

mkdir tworld-$VER
tar -cf - `cat MANIFEST` | tar -C tworld-$VER -xf -
rm -f tworld-$VER.tar.gz
tar -cvf tworld-$VER.tar tworld-$VER
gzip -9 tworld-$VER.tar
rm -rf tworld-$VER
