#!/bin/bash

#
# Update the documentation files.
#

html2txt < ./README.html > ./README
html2txt < ./BUGS.html > ./BUGS
html2txt < ./INSTALL.html > ./INSTALL
html2txt < ./Changelog.html > ./Changelog

(cd docs && ./mkdocs tworld.doc)

#
# Tar everything up in a fresh versioned directory.
#

VER=`sed -e 's/^.*"\(.*\)".*$/\1/' < ver.h`
mkdir tworld-$VER
tar -cf - `cat MANIFEST` | tar -C tworld-$VER -xf -
rm -f tworld-$VER.tar.gz
tar -cvf tworld-$VER.tar tworld-$VER
gzip -9 tworld-$VER.tar
rm -rf tworld-$VER

#
# Finally, grab the files to update on the website.
#

rm -f twdocs.tar twdocs.tar.gz INSTALL-linux.html INSTALL-win32.html
cp INSTALL.html INSTALL-linux.html
cp win32/INSTALL.html INSTALL-win32.html
tar -cf twdocs.tar README.html INSTALL-linux.html INSTALL-win32.html \
                   BUGS.html Changelog.html
gzip -9 twdocs.tar
rm INSTALL-linux.html INSTALL-win32.html
