#!/bin/bash

cd win32
if test -d build ; then rm -rf build ; fi
mkdir build
cd build

mkdir oshw-sdl
ln -s oshw-sdl oshw
mkdir resources
mkdir data
mkdir sets
mkdir docs
for f in `cat ../../MANIFEST` ; do cp -a ../../$f ./$f ; done
for f in `cat ../BUILDFILES` ; do cp -a ../$f ./$f ; done

sh ./cross-configure.sh --with-win32
sh ./cross-make.sh tworld.exe

/home/breadbox/p/html2txt < ../../README.html > README.txt
/home/breadbox/p/html2txt < ../INSTALL.html > INSTALL.txt
/home/breadbox/p/html2txt < ../../BUGS.html > BUGS.txt
/home/breadbox/p/html2txt < ../../Changelog.html > Changelog.txt
mv COPYING COPYING.txt
mv -i docs/*.html .
mv resources res

VER=`tr -cd 0123456789. < ver.h`

zip -9 -l tworld-$VER-win32.zip README.txt INSTALL.txt Changelog.txt BUGS.txt
zip -9 -l tworld-$VER-win32.zip COPYING.txt README-SDL.txt
zip -9    tworld-$VER-win32.zip tworld.exe SDL.dll mklynxcc.com
zip -9 -l tworld-$VER-win32.zip tworld.html sets/*.dac res/rc
zip -9    tworld-$VER-win32.zip res/*.bmp res/*.wav data/*.dat

rm -f ../../tworld-$VER-win32.zip
mv tworld-$VER-win32.zip ../..
cd ..
rm -rf build
cd ..
